version: '3.3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: front.Dockerfile
    ports:
      - "4200:80"
    expose:
      - "4200"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge